---
logging:
  prod: false
  log_level: debug

directory_service:
  config:
    db_path: /tmp/edgeds.db
    seed_metadata: false
    address: localhost:9292
    insecure: true

api:
  grpc:
    connection_timeout_seconds: 2

opa:
  instance_id: 5d7cccc6-1657-11ec-a291-00001df0866c                                   
  graceful_shutdown_period_seconds: 2                                                 
  local_bundles:                                                                      
    paths: []                                                                         
    skip_verification: true                                                           
  config:
    services:
      acmecorp:
        url: https://ghcr.io/
        type: "oci"
        response_header_timeout_seconds: 5
    bundles:
      peoplefinder:
        service: acmecorp
        resource: "ghcr.io/aserto-policies/policy-peoplefinder-rbac:latest"
        persist: false
        config:
          polling:
            min_delay_seconds: 60
            max_delay_seconds: 120
