---
logging:
  prod: false
  log_level: debug

directory_service:
  path: ""

api:
  grpc:
    connection_timeout_seconds: 2
  metrics:
    zpages: true
    grpc:
      counters: true
      durations: true
      gateway: true

opa:
  instance_id: 5d7cccc6-1657-11ec-a291-00001df0866c
  graceful_shutdown_period_seconds: 2
  local_bundles:
    paths: []
    skip_verification: true
