---
logging:
  prod: false
  log_level: debug

directory:
    db_path: .dev/test.db
    seed_metadata: true

api:
  authorizer:
    gateway:
      listen_address: "0.0.0.0:8383"
    grpc:
      listen_address: "0.0.0.0:8282"
      connection_timeout_seconds: 120
    health:
      listen_address: "0.0.0.0:8484"

opa:
  instance_id: 5d7cccc6-1657-11ec-a291-00001df0866c
  graceful_shutdown_period_seconds: 2
  local_bundles:
    paths: []
    skip_verification: true
