---
logging:
  prod: false
  log_level: debug

directory:
    db_path: .dev/test.db
    seed_metadata: true

directory_resolver:
  address: localhost:9292
  insecure: true

api:
  authorizer:
    grpc:
      connection_timeout_seconds: 2

opa:
  instance_id: 5d7cccc6-1657-11ec-a291-00001df0866c
  graceful_shutdown_period_seconds: 2
  local_bundles:
    paths: []
    skip_verification: true
