---
logging:
  prod: false
  log_level: debug

directory_service:
  edge:
    db_path: /tmp/edgeds.db
    seed_metadata: false
  remote:
    address: "localhost:9292"
    insecure: true

api:
  grpc:
    connection_timeout_seconds: 2

opa:
  instance_id: 5d7cccc6-1657-11ec-a291-00001df0866c
  graceful_shutdown_period_seconds: 2
  local_bundles:
    paths: []
    skip_verification: true
