---
# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration

linters:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    # - containedctx
    # - contextcheck
    - copyloopvar
    # - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    # - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl
    - zerologlint

  # explicitly disabled linters
  disable:
    - depguard
    - exhaustruct
    - exhaustive
    - forbidigo
    - gci # use gofumpt
    - gochecknoglobals # no configuration options
    - nilnil
    - nlreturn # redundant with wsl
    - paralleltest
    - revive
    - tagalign
    - thelper
    - varnamelen
    - wrapcheck

  exclusions:
    rules:
      - path: pkg/app/tests/
        linters:
        - dupl
        - forbidigo
        - wsl
      
      - path: internal/pkg/xdg/
        linters:
          - gochecknoinits
          - mnd
          - testableexamples
          - usetesting
          - wsl

      - path: pkg/cc/signals/
        linters:
          - mnd

      - path: pkg/cli/cmd/
        linters:
          - dupl

      - path: pkg/cli/editor/
        linters:
          - dupword
          - errorlint
          - forcetypeassert
          - gocritic
          - godox
          - mnd
          - ireturn
          - lll
          - makezero
          - nonamedreturns
          - recvcheck
          - wsl

      - path: pkg/app/handlers/authorizer.go
        linters:
          - tagliatelle

      - path: pkg/app/handlers/config.go
        linters:
          - tagliatelle

      - path: cmd/topaz-db/
        linters:
          - staticcheck

linters-settings:
  cyclop:
    max-complexity: 12

  funlen:
    lines: 80
    statements: 60
    ignore-comments: true

  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
      - plugins.Factory
      - plugins.Plugin
      - proto.Message
      - v3.ReaderClient
      - resolvers.DirectoryResolver
      - resolvers.RuntimeResolver
      - decisionlog.DecisionLogger

  lll:
    line-length: 150

  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
