---
# Configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  # https://golangci-lint.run/usage/configuration/#linters-configuration
  default: all

  # explicitly disabled linters
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - errcheck
    - exhaustruct
    - exhaustive
    - forbidigo
    - gochecknoglobals  # no configuration options
    - nilnil
    - nlreturn          # redundant with wsl
    - paralleltest
    - revive
    - tagalign
    - thelper
    - varnamelen
    - wrapcheck

  exclusions:
    generated: lax

    rules:
      - path: pkg/app/tests/
        linters:
        - dupl
        - forbidigo
        - wsl
      
      - path: internal/pkg/xdg/
        linters:
          - gochecknoinits
          - gosec
          - mnd
          - testableexamples
          - testifylint
          - usetesting
          - wsl

      - path: pkg/cc/signals/
        linters:
          - mnd

      - path: pkg/cli/cmd/
        linters:
          - dupl

      - path: pkg/cli/editor/
        linters:
          - dupword
          - errcheck
          - errorlint
          - forcetypeassert
          - gocritic
          - godox
          - gosec
          - mnd
          - ireturn
          - lll
          - makezero
          - nonamedreturns
          - recvcheck
          - wsl

      - path: pkg/app/handlers/authorizer.go
        linters:
          - tagliatelle

      - path: pkg/app/handlers/config.go
        linters:
          - tagliatelle

      - path: cmd/topaz-db/
        linters:
          - staticcheck


  settings:
    cyclop:
      max-complexity: 12

    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.Close

    funlen:
      lines: 80
      statements: 60
      ignore-comments: true

    gomoddirectives:
      replace-allow-list:
        - github.com/slok/go-http-metrics

    gosec:
      excludes:
        - G104 # Errors unhandled 
        - G304 # Potential file inclusion via variable (see https://github.com/golang/go/issues/67002)

    ireturn:
      allow:
        # stdlib
        - anon
        - error
        - empty
        - stdlib
        - generic
        - context.Context
        - http.Handler
        - io.Reader
        # 3rd-party
        - credentials.TransportCredentials
        - jwt.Token
        - metrics.Recorder
        - testcontainers-go.Container
        - plugins.Factory
        - plugins.Plugin
        - proto.Message
        - v3.ReaderClient
        - resolvers.DirectoryResolver
        - resolvers.RuntimeResolver
        - decisionlog.DecisionLogger

    lll:
      line-length: 150

    recvcheck:
      exclusions:
        - "*.UnmarshalGQL"

    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
