before:
  hooks:

builds:
  - id: topazd
    main: ./cmd/topazd
    binary: topazd
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/topaz/pkg/version.ver={{.Version}}
      - -X github.com/aserto-dev/topaz/pkg/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/topaz/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: topaz
    main: ./cmd/topaz
    binary: topaz
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/aserto-dev/topaz/pkg/version.ver={{.Version}}
      - -X github.com/aserto-dev/topaz/pkg/version.commit={{.ShortCommit}}
      - -X github.com/aserto-dev/topaz/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: zip
    builds:
    - topaz
    - topazd
    files:
      - LICENSE
      - README.md
    name_template: >-
      topaz_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}
    
    rlcp: true

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: aserto-dev
    name: topaz

  draft: false
  prerelease: false
  name_template: "topaz {{.Tag}}"

blobs:
  -
    provider: gs
    bucket: topaz-cli
    folder: "topaz/{{ .Version }}"
    extra_files:
      - glob: VERSION.txt
  -
    provider: gs
    bucket: topaz-cli
    folder: "topaz/latest"
    extra_files:
      - glob: VERSION.txt

brews:
  -
    name: topaz

    tap:
      owner: aserto-dev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP }}"

    url_template: "https://storage.googleapis.com/topaz-cli/topaz/{{ .Version }}/{{ .ArtifactName }}"

    download_strategy: CurlDownloadStrategy

    commit_author:
      name: Aserto Bot
      email: github-bot@aserto.com

    homepage: "https://www.topaz.sh/docs/"

    description: "Topaz CLI"

    license: "MIT"

    skip_upload: false

    test: |
      system "#{bin}/topaz version"
    install: |
      bin.install "topaz"
