version: 2

project_name: topaz

env:
  # https://goreleaser.com/customization/env/
  - REGISTRY=ghcr.io
  - ORG=aserto-dev
  - REPO=topaz
  - DESCRIPTION="Topaz Authorization Service"
  - LICENSE=Apache-2.0

before:
  # https://goreleaser.com/customization/hooks/
  hooks:

builds:
  # https://goreleaser.com/customization/build/
  - id: topazd
    main: ./topazd
    binary: topazd
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/topazd/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/topazd/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/topazd/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: topaz
    main: ./topaz
    binary: topaz
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/topaz/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/topaz/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/topaz/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: topaz-db
    main: ./topaz-db
    binary: topaz-db
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: topaz-backup
    main: ./topaz-backup
    binary: topaz-backup
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  # https://goreleaser.com/customization/archive/
  - formats:
      - zip
    ids:
      - topaz
      - topazd
      - topaz-backup
    files:
      - LICENSE
      - README.md
    name_template: >-
      topaz_{{ .Os }}_{{ .Arch }}

checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: "checksums.txt"

snapshot:
  # https://goreleaser.com/customization/snapshots/
  version_template: "{{ incpatch .Version }}-{{ .ShortCommit }}{{ if .IsGitDirty }}-dirty{{ end }}"

source:
  # https://goreleaser.com/customization/source/
  enabled: false

changelog:
  # https://goreleaser.com/customization/changelog/
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  # https://goreleaser.com/customization/release/
  github:
    owner: "{{ .Env.ORG }}"
    name: "{{ .Env.REPO }}"

  draft: false
  prerelease: "false"
  name_template: "{{.ProjectName}} {{.Tag}}"

blobs:
  # https://goreleaser.com/customization/blob/

homebrew_casks:
  # https://goreleaser.com/customization/homebrew_casks/
  - name: topaz

    repository:
      owner: "{{ .Env.ORG }}"
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP }}"

    url:
      verified: "github.com/{{ .Env.ORG }}/{{ .ProjectName }}"

    commit_author:
      name: Topaz Bot
      email: info@topaz.sh

    homepage: "https://www.topaz.sh/docs/"
    description: "Topaz CLI"
    license: "MIT"

    binaries:
      - topaz

    skip_upload: false

    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/topaz"]
          end

dockers_v2:
  # https://goreleaser.com/customization/dockers_v2
  - dockerfile: "Dockerfile"

    platforms:
      - linux/amd64
      - linux/arm64

    ids:
      - topaz
      - topazd
      - topaz-backup

    images:
      - "{{ .Env.REGISTRY }}/{{ .Env.ORG }}/{{ .Env.REPO }}"

    tags:
      - "{{ .Version }}"
      - "{{ if not .IsSnapshot }}latest{{ end }}"

    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/{{ .Env.ORG }}/{{ .Env.REPO }}"
      "org.opencontainers.image.description": "{{ .Env.DESCRIPTION }}"
      "org.opencontainers.image.licenses": "{{ .Env.LICENSE }}"

    sbom: false # Attestation is not supported for the docker driver.

    retry:
      attempts: 10
      delay: 10s
      max_delay: 2m

    extra_files:
    annotations:
    build_args:
    flags:

sboms:
  # https://goreleaser.com/customization/sbom/
  - id: default
    documents:
      - "${artifact}-{{.Os}}-{{.Arch}}.spdx.sbom.json"
    cmd: syft
    args:
      - "$artifact"
      - "--output"
      - "spdx-json=$document"
    env:
      - SYFT_FILE_METADATA_CATALOGER_ENABLED=true
    artifacts: binary
    ids:
      - topaz
      - topazd
      - topaz-backup
      - topaz-db
