version: 2

project_name: topaz

env:
  # https://goreleaser.com/customization/env/
  - REGISTRY=ghcr.io
  - ORG=aserto-dev
  - REPO=topaz
  - DESCRIPTION="Topaz Authorization Service"
  - LICENSE=Apache-2.0

before:
  # https://goreleaser.com/customization/hooks/
  hooks:

# https://goreleaser.com/customization/dist/
dist: dist-test

builds:
  # https://goreleaser.com/customization/build/
  - id: topazd
    main: ./topazd
    binary: topazd
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post: make container-tag

  - id: topaz
    main: ./topaz
    binary: topaz
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: topaz-backup
    main: ./topaz-backup
    binary: topaz-backup
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

snapshot:
  # https://goreleaser.com/customization/snapshots/
  version_template: "0.0.0-test-{{ .ShortCommit }}"

dockers_v2:
  # https://goreleaser.com/customization/dockers_v2
  - dockerfile: "Dockerfile"

    platforms:
      - linux/arm64
      - linux/amd64

    ids:
      - topaz
      - topazd
      - topaz-backup

    images:
      - "{{ .Env.REGISTRY }}/{{ .Env.ORG }}/{{ .Env.REPO }}"

    tags:
      - "{{ .Version }}"

    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "https://github.com/{{ .Env.ORG }}/{{ .Env.REPO }}"
      "org.opencontainers.image.description": "{{ .Env.DESCRIPTION }}"
      "org.opencontainers.image.licenses": "{{ .Env.LICENSE }}"

    sbom: false # Attestation is not supported for the docker driver.

    retry:
      attempts: 10
      delay: 10s
      max_delay: 2m

    extra_files:
    annotations:
    build_args:
    flags:
