project_name: topaz

env:
  - REGISTRY=ghcr.io
  - ORG=aserto-dev
  - REPO=topaz

before:
  # https://goreleaser.com/customization/hooks/
  hooks:
      - ./pre-build.sh {{ .Env.CONSOLE_VERSION }}

builds:
  # https://goreleaser.com/customization/build/
  - id: topazd
    main: ./cmd/topazd
    binary: topazd
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: topaz
    main: ./cmd/topaz
    binary: topaz
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.ver={{.Version}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.commit={{.ShortCommit}}
      - -X github.com/{{ .Env.ORG }}/{{ .Env.REPO }}/pkg/version.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  # https://goreleaser.com/customization/archive/
  - format: zip
    builds:
    - topaz
    - topazd
    files:
      - LICENSE
      - README.md
    name_template: >-
      topaz_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}

checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: "checksums.txt"

snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: "{{ .Tag }}"

source:
  # https://goreleaser.com/customization/source/
  enabled: false

changelog:
  # https://goreleaser.com/customization/changelog/
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  # https://goreleaser.com/customization/release/
  # github:
  #   owner: "{{ .Env.ORG }}"
  #   name: "{{ .Env.REPO }}"

  # draft: false
  # prerelease: false
  # name_template: "{{.ProjectName}} {{.Tag}}"

blobs:
  # https://goreleaser.com/customization/blob/
  # -
  #   provider: gs
  #   bucket: topaz-cli
  #   folder: "topaz/{{ .Version }}"
  #   extra_files:
  #     - glob: VERSION.txt
  # -
  #   provider: gs
  #   bucket: topaz-cli
  #   folder: "topaz/latest"
  #   extra_files:
  #     - glob: VERSION.txt

brews:
  # https://goreleaser.com/customization/homebrew/
  # -
  #   name: topaz

  #   repository:
  #     owner: "{{ .Env.ORG }}"
  #     name: homebrew-tap
  #     token: "{{ .Env.ASERTO_TAP }}"

  #   url_template: "https://storage.googleapis.com/topaz-cli/topaz/{{ .Version }}/{{ .ArtifactName }}"

  #   download_strategy: CurlDownloadStrategy

  #   commit_author:
  #     name: Aserto Bot
  #     email: github-bot@aserto.com

  #   homepage: "https://www.topaz.sh/docs/"

  #   description: "Topaz CLI"

  #   license: "MIT"

  #   skip_upload: false

  #   test: |
  #     system "#{bin}/topaz version"
  #   install: |
  #     bin.install "topaz"

dockers:
  # https://goreleaser.com/customization/docker/
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - &amd64-image "{{ .Env.REGISTRY }}/{{ .Env.ORG }}/{{ .Env.REPO }}:v3-latest-test-amd64"
    skip_push: false
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=v3-latest-test-amd64"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.ORG }}/{{ .Env.REPO }}"
      - "--label=org.opencontainers.image.description=Topaz"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - &amd64-image "{{ .Env.REGISTRY }}/{{ .Env.ORG }}/{{ .Env.REPO }}:v3-latest-test-amd64"
    skip_push: false
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version=v3-latest-test-arm64"
      - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.ORG }}/{{ .Env.REPO }}"
      - "--label=org.opencontainers.image.description=Topaz"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

