FROM alpine

RUN apk add --no-cache bash tzdata

RUN mkdir /config && \
    mkdir /certs && \
    mkdir /db && \
    mkdir /decisions
VOLUME ["/config", "/certs", "/db", "/decisions"]

WORKDIR /app

COPY topaz* /app/

ENTRYPOINT ["./topazd", "run", "-c"]
CMD ["/config/config.yaml"]
