FROM alpine

ARG GOARCH
ARG TARGETOS
ARG TARGETARCH

RUN apk add --no-cache bash tzdata ca-certificates

RUN mkdir /config && \
    mkdir /certs && \
    mkdir /db && \
    mkdir /decisions
VOLUME ["/config", "/certs", "/db", "/decisions"]

WORKDIR /app

COPY topazd topaz /app/

ENTRYPOINT ["./topazd"]
CMD ["run", "-c", "/config/config.yaml"]
