#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

BIN_NAME=$1

BIN_PATH=${PWD}/dist/${BIN_NAME}_$(go env GOOS)_$(go env GOARCH)

if [[ -n $(go env GOARM64) ]] then 
  BIN_PATH+="_"$(go env GOARM64)
fi 

BIN_PATH+="/${BIN_NAME}"

if [ ! -f $BIN_PATH ]; then
    echo "local binary \"${BIN_PATH}\" not found!"
fi

shift 

echo "xb ${BIN_PATH} $*"

${BIN_PATH} $*
