# In this example configuration to allow topaz to interact with the Aserto Directory service you will need to fill in your directory access key and your tenant ID. 
# You can find these values in the Aserto Console: for the directory access key you will find these values in the connections tab for Aserto Directory and to you will find the tenant ID in your account settings. 
# In this example, as we use the policy todo image, we recommend setting up a Demo Citadel IDP connection to exercise the example policy paths with the users that have the correct permissions. 

---
logging:
  prod: true
  log_level: debug


remote_directory:
  address: "directory.prod.aserto.com:8443"
  api_key: <Your Aserto Directory Access Key>
  tenant_id: <Your Aserto Tenant ID>

api:
  authorizer:
    gateway:
      allowed_origins:
      - https://localhost
    grpc:
      connection_timeout_seconds: 2

opa:
  instance_id: "-"
  graceful_shutdown_period_seconds: 2
  local_bundles:
    paths: []
    skip_verification: true
  config:
    services:
      acmecorp:
        url: https://ghcr.io/
        type: "oci"
        response_header_timeout_seconds: 5
    bundles:
      peoplefinder:
        service: acmecorp
        resource: "ghcr.io/aserto-policies/policy-todo-rebac:latest"
        persist: false
        config:
          polling:
            min_delay_seconds: 60
            max_delay_seconds: 120