# To use a private policy image you need to fill the following configuation with the required information:
# 1. Github PAT with the available rights to access private packages.
# 2. Your organization
# 3. Your policy image name and label
---
version: 2
logging:
  prod: true
  log_level: debug

api:
  services:
    authorizer:
      gateway:
        allowed_origins:
        - https://localhost
      grpc:
        listen_address: "0.0.0.0:8282"
        connection_timeout_seconds: 2

opa:
  instance_id: "-"
  graceful_shutdown_period_seconds: 2
  local_bundles:
    paths: []
    skip_verification: true
  config:
    services:
      acmecorp:
        url: https://ghcr.io/
        type: "oci"
        response_header_timeout_seconds: 5
        credentials:
          bearer:
            schema: "Basic"
            token: "<your_pat>"
    bundles:
      peoplefinder:
        service: acmecorp
        resource: "ghcr.io/<org>/<policy image name>:<policy image tag>"
        persist: false
        config:
          polling:
            min_delay_seconds: 60
            max_delay_seconds: 120