// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/reader/export.proto

package reader

import (
	v4 "github.com/aserto-dev/topaz/api/directory/v4"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Option int32

const (
	// nothing selected (default initialization value)
	Option_OPTION_UNKNOWN Option = 0
	// object instances
	Option_OPTION_DATA_OBJECTS Option = 8
	// relation instances
	Option_OPTION_DATA_RELATIONS Option = 16
	// all data = OPTION_DATA_OBJECTS | OPTION_DATA_RELATIONS
	Option_OPTION_DATA Option = 24
	// stats
	Option_OPTION_STATS Option = 64
)

// Enum value maps for Option.
var (
	Option_name = map[int32]string{
		0:  "OPTION_UNKNOWN",
		8:  "OPTION_DATA_OBJECTS",
		16: "OPTION_DATA_RELATIONS",
		24: "OPTION_DATA",
		64: "OPTION_STATS",
	}
	Option_value = map[string]int32{
		"OPTION_UNKNOWN":        0,
		"OPTION_DATA_OBJECTS":   8,
		"OPTION_DATA_RELATIONS": 16,
		"OPTION_DATA":           24,
		"OPTION_STATS":          64,
	}
)

func (x Option) Enum() *Option {
	p := new(Option)
	*p = x
	return p
}

func (x Option) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Option) Descriptor() protoreflect.EnumDescriptor {
	return file_directory_v4_reader_export_proto_enumTypes[0].Descriptor()
}

func (Option) Type() protoreflect.EnumType {
	return &file_directory_v4_reader_export_proto_enumTypes[0]
}

func (x Option) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Option.Descriptor instead.
func (Option) EnumDescriptor() ([]byte, []int) {
	return file_directory_v4_reader_export_proto_rawDescGZIP(), []int{0}
}

type ExportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data export options mask
	Options uint32 `protobuf:"varint,1,opt,name=options,proto3" json:"options,omitempty"`
	// start export from timestamp (UTC)
	StartFrom     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=start_from,json=startFrom,proto3" json:"start_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_directory_v4_reader_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportRequest) GetOptions() uint32 {
	if x != nil {
		return x.Options
	}
	return 0
}

func (x *ExportRequest) GetStartFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.StartFrom
	}
	return nil
}

type ExportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExportResponse_Object
	//	*ExportResponse_Relation
	//	*ExportResponse_Stats
	Msg           isExportResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_directory_v4_reader_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportResponse) GetMsg() isExportResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExportResponse) GetObject() *v4.Object {
	if x != nil {
		if x, ok := x.Msg.(*ExportResponse_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *ExportResponse) GetRelation() *v4.Relation {
	if x != nil {
		if x, ok := x.Msg.(*ExportResponse_Relation); ok {
			return x.Relation
		}
	}
	return nil
}

func (x *ExportResponse) GetStats() *structpb.Struct {
	if x != nil {
		if x, ok := x.Msg.(*ExportResponse_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isExportResponse_Msg interface {
	isExportResponse_Msg()
}

type ExportResponse_Object struct {
	// object instance (data)
	Object *v4.Object `protobuf:"bytes,2,opt,name=object,proto3,oneof"`
}

type ExportResponse_Relation struct {
	// relation instance (data)
	Relation *v4.Relation `protobuf:"bytes,4,opt,name=relation,proto3,oneof"`
}

type ExportResponse_Stats struct {
	// object and/or relation stats (no data)
	Stats *structpb.Struct `protobuf:"bytes,8,opt,name=stats,proto3,oneof"`
}

func (*ExportResponse_Object) isExportResponse_Msg() {}

func (*ExportResponse_Relation) isExportResponse_Msg() {}

func (*ExportResponse_Stats) isExportResponse_Msg() {}

var File_directory_v4_reader_export_proto protoreflect.FileDescriptor

const file_directory_v4_reader_export_proto_rawDesc = "" +
	"\n" +
	" directory/v4/reader/export.proto\x12\x13directory.v4.reader\x1a\x19directory/v4/object.proto\x1a\x1bdirectory/v4/relation.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\rExportRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\rR\aoptions\x129\n" +
	"\n" +
	"start_from\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tstartFrom\"\xae\x01\n" +
	"\x0eExportResponse\x12.\n" +
	"\x06object\x18\x02 \x01(\v2\x14.directory.v4.ObjectH\x00R\x06object\x124\n" +
	"\brelation\x18\x04 \x01(\v2\x16.directory.v4.RelationH\x00R\brelation\x12/\n" +
	"\x05stats\x18\b \x01(\v2\x17.google.protobuf.StructH\x00R\x05statsB\x05\n" +
	"\x03msg*s\n" +
	"\x06Option\x12\x12\n" +
	"\x0eOPTION_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13OPTION_DATA_OBJECTS\x10\b\x12\x19\n" +
	"\x15OPTION_DATA_RELATIONS\x10\x10\x12\x0f\n" +
	"\vOPTION_DATA\x10\x18\x12\x10\n" +
	"\fOPTION_STATS\x10@B<Z:github.com/aserto-dev/topaz/api/directory/v4/reader;readerb\x06proto3"

var (
	file_directory_v4_reader_export_proto_rawDescOnce sync.Once
	file_directory_v4_reader_export_proto_rawDescData []byte
)

func file_directory_v4_reader_export_proto_rawDescGZIP() []byte {
	file_directory_v4_reader_export_proto_rawDescOnce.Do(func() {
		file_directory_v4_reader_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_reader_export_proto_rawDesc), len(file_directory_v4_reader_export_proto_rawDesc)))
	})
	return file_directory_v4_reader_export_proto_rawDescData
}

var file_directory_v4_reader_export_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_directory_v4_reader_export_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_directory_v4_reader_export_proto_goTypes = []any{
	(Option)(0),                   // 0: directory.v4.reader.Option
	(*ExportRequest)(nil),         // 1: directory.v4.reader.ExportRequest
	(*ExportResponse)(nil),        // 2: directory.v4.reader.ExportResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*v4.Object)(nil),             // 4: directory.v4.Object
	(*v4.Relation)(nil),           // 5: directory.v4.Relation
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
}
var file_directory_v4_reader_export_proto_depIdxs = []int32{
	3, // 0: directory.v4.reader.ExportRequest.start_from:type_name -> google.protobuf.Timestamp
	4, // 1: directory.v4.reader.ExportResponse.object:type_name -> directory.v4.Object
	5, // 2: directory.v4.reader.ExportResponse.relation:type_name -> directory.v4.Relation
	6, // 3: directory.v4.reader.ExportResponse.stats:type_name -> google.protobuf.Struct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_directory_v4_reader_export_proto_init() }
func file_directory_v4_reader_export_proto_init() {
	if File_directory_v4_reader_export_proto != nil {
		return
	}
	file_directory_v4_reader_export_proto_msgTypes[1].OneofWrappers = []any{
		(*ExportResponse_Object)(nil),
		(*ExportResponse_Relation)(nil),
		(*ExportResponse_Stats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_reader_export_proto_rawDesc), len(file_directory_v4_reader_export_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_reader_export_proto_goTypes,
		DependencyIndexes: file_directory_v4_reader_export_proto_depIdxs,
		EnumInfos:         file_directory_v4_reader_export_proto_enumTypes,
		MessageInfos:      file_directory_v4_reader_export_proto_msgTypes,
	}.Build()
	File_directory_v4_reader_export_proto = out.File
	file_directory_v4_reader_export_proto_goTypes = nil
	file_directory_v4_reader_export_proto_depIdxs = nil
}
