// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/reader/graph.proto

package reader

import (
	v4 "github.com/aserto-dev/topaz/api/directory/v4"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier
	ObjectType string `protobuf:"bytes,3,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier (optional)
	ObjectId string `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,5,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type identifier
	SubjectType string `protobuf:"bytes,6,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject instance identifier (optional)
	SubjectId string `protobuf:"bytes,7,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// subject relation name (optional)
	SubjectRelation string `protobuf:"bytes,8,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// return graph paths for each result (optional)
	Explain bool `protobuf:"varint,9,opt,name=explain,proto3" json:"explain,omitempty"`
	// collect trace information (optional)
	Trace         bool `protobuf:"varint,10,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphRequest) Reset() {
	*x = GraphRequest{}
	mi := &file_directory_v4_reader_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRequest) ProtoMessage() {}

func (x *GraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRequest.ProtoReflect.Descriptor instead.
func (*GraphRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_graph_proto_rawDescGZIP(), []int{0}
}

func (x *GraphRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GraphRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GraphRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GraphRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *GraphRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GraphRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *GraphRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

func (x *GraphRequest) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

type GraphResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// matching object identifiers
	Results []*v4.ObjectIdentifier `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// explanation of results
	Explanation *structpb.Struct `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// trace information
	Trace         []string `protobuf:"bytes,4,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphResponse) Reset() {
	*x = GraphResponse{}
	mi := &file_directory_v4_reader_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphResponse) ProtoMessage() {}

func (x *GraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphResponse.ProtoReflect.Descriptor instead.
func (*GraphResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_graph_proto_rawDescGZIP(), []int{1}
}

func (x *GraphResponse) GetResults() []*v4.ObjectIdentifier {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GraphResponse) GetExplanation() *structpb.Struct {
	if x != nil {
		return x.Explanation
	}
	return nil
}

func (x *GraphResponse) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

var File_directory_v4_reader_graph_proto protoreflect.FileDescriptor

const file_directory_v4_reader_graph_proto_rawDesc = "" +
	"\n" +
	"\x1fdirectory/v4/reader/graph.proto\x12\x13directory.v4.reader\x1a$directory/v4/object_identifier.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xad\x02\n" +
	"\fGraphRequest\x12$\n" +
	"\vobject_type\x18\x03 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x04 \x01(\tB\x03\xe0A\x01R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x05 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x06 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\a \x01(\tB\x03\xe0A\x01R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\b \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\x12\x1d\n" +
	"\aexplain\x18\t \x01(\bB\x03\xe0A\x01R\aexplain\x12\x19\n" +
	"\x05trace\x18\n" +
	" \x01(\bB\x03\xe0A\x01R\x05trace\"\x9a\x01\n" +
	"\rGraphResponse\x128\n" +
	"\aresults\x18\x02 \x03(\v2\x1e.directory.v4.ObjectIdentifierR\aresults\x129\n" +
	"\vexplanation\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vexplanation\x12\x14\n" +
	"\x05trace\x18\x04 \x03(\tR\x05traceB<Z:github.com/aserto-dev/topaz/api/directory/v4/reader;readerb\x06proto3"

var (
	file_directory_v4_reader_graph_proto_rawDescOnce sync.Once
	file_directory_v4_reader_graph_proto_rawDescData []byte
)

func file_directory_v4_reader_graph_proto_rawDescGZIP() []byte {
	file_directory_v4_reader_graph_proto_rawDescOnce.Do(func() {
		file_directory_v4_reader_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_reader_graph_proto_rawDesc), len(file_directory_v4_reader_graph_proto_rawDesc)))
	})
	return file_directory_v4_reader_graph_proto_rawDescData
}

var file_directory_v4_reader_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_directory_v4_reader_graph_proto_goTypes = []any{
	(*GraphRequest)(nil),        // 0: directory.v4.reader.GraphRequest
	(*GraphResponse)(nil),       // 1: directory.v4.reader.GraphResponse
	(*v4.ObjectIdentifier)(nil), // 2: directory.v4.ObjectIdentifier
	(*structpb.Struct)(nil),     // 3: google.protobuf.Struct
}
var file_directory_v4_reader_graph_proto_depIdxs = []int32{
	2, // 0: directory.v4.reader.GraphResponse.results:type_name -> directory.v4.ObjectIdentifier
	3, // 1: directory.v4.reader.GraphResponse.explanation:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_directory_v4_reader_graph_proto_init() }
func file_directory_v4_reader_graph_proto_init() {
	if File_directory_v4_reader_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_reader_graph_proto_rawDesc), len(file_directory_v4_reader_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_reader_graph_proto_goTypes,
		DependencyIndexes: file_directory_v4_reader_graph_proto_depIdxs,
		MessageInfos:      file_directory_v4_reader_graph_proto_msgTypes,
	}.Build()
	File_directory_v4_reader_graph_proto = out.File
	file_directory_v4_reader_graph_proto_goTypes = nil
	file_directory_v4_reader_graph_proto_depIdxs = nil
}
