// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/reader/manifest.proto

package reader

import (
	v4 "github.com/aserto-dev/topaz/api/directory/v4"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_directory_v4_reader_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *GetManifestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *v4.Manifest           `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_directory_v4_reader_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *GetManifestResponse) GetManifest() *v4.Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

var File_directory_v4_reader_manifest_proto protoreflect.FileDescriptor

const file_directory_v4_reader_manifest_proto_rawDesc = "" +
	"\n" +
	"\"directory/v4/reader/manifest.proto\x12\x13directory.v4.reader\x1a\x1bdirectory/v4/manifest.proto\"$\n" +
	"\x12GetManifestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x13GetManifestResponse\x122\n" +
	"\bmanifest\x18\x01 \x01(\v2\x16.directory.v4.ManifestR\bmanifestB<Z:github.com/aserto-dev/topaz/api/directory/v4/reader;readerb\x06proto3"

var (
	file_directory_v4_reader_manifest_proto_rawDescOnce sync.Once
	file_directory_v4_reader_manifest_proto_rawDescData []byte
)

func file_directory_v4_reader_manifest_proto_rawDescGZIP() []byte {
	file_directory_v4_reader_manifest_proto_rawDescOnce.Do(func() {
		file_directory_v4_reader_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_reader_manifest_proto_rawDesc), len(file_directory_v4_reader_manifest_proto_rawDesc)))
	})
	return file_directory_v4_reader_manifest_proto_rawDescData
}

var file_directory_v4_reader_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_directory_v4_reader_manifest_proto_goTypes = []any{
	(*GetManifestRequest)(nil),  // 0: directory.v4.reader.GetManifestRequest
	(*GetManifestResponse)(nil), // 1: directory.v4.reader.GetManifestResponse
	(*v4.Manifest)(nil),         // 2: directory.v4.Manifest
}
var file_directory_v4_reader_manifest_proto_depIdxs = []int32{
	2, // 0: directory.v4.reader.GetManifestResponse.manifest:type_name -> directory.v4.Manifest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_directory_v4_reader_manifest_proto_init() }
func file_directory_v4_reader_manifest_proto_init() {
	if File_directory_v4_reader_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_reader_manifest_proto_rawDesc), len(file_directory_v4_reader_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_reader_manifest_proto_goTypes,
		DependencyIndexes: file_directory_v4_reader_manifest_proto_depIdxs,
		MessageInfos:      file_directory_v4_reader_manifest_proto_msgTypes,
	}.Build()
	File_directory_v4_reader_manifest_proto = out.File
	file_directory_v4_reader_manifest_proto_goTypes = nil
	file_directory_v4_reader_manifest_proto_depIdxs = nil
}
