// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/reader/object.proto

package reader

import (
	v4 "github.com/aserto-dev/topaz/api/directory/v4"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// materialize the object relations objects (optional)
	WithRelations bool `protobuf:"varint,3,opt,name=with_relations,json=withRelations,proto3" json:"with_relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_directory_v4_reader_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_object_proto_rawDescGZIP(), []int{0}
}

func (x *GetObjectRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetObjectRequest) GetWithRelations() bool {
	if x != nil {
		return x.WithRelations
	}
	return false
}

type GetObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object instance
	Result *v4.Object `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// object relations
	Relations     []*v4.Relation `protobuf:"bytes,4,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_directory_v4_reader_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_object_proto_rawDescGZIP(), []int{1}
}

func (x *GetObjectResponse) GetResult() *v4.Object {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetObjectResponse) GetRelations() []*v4.Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type ListObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier (optional)
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// pagination request (optional)
	Page          *v4.PaginationRequest `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_directory_v4_reader_object_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_object_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_object_proto_rawDescGZIP(), []int{2}
}

func (x *ListObjectsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ListObjectsRequest) GetPage() *v4.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListObjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of object instances
	Results []*v4.Object `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// pagination response
	Page          *v4.PaginationResponse `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_directory_v4_reader_object_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_object_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_object_proto_rawDescGZIP(), []int{3}
}

func (x *ListObjectsResponse) GetResults() []*v4.Object {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListObjectsResponse) GetPage() *v4.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_directory_v4_reader_object_proto protoreflect.FileDescriptor

const file_directory_v4_reader_object_proto_rawDesc = "" +
	"\n" +
	" directory/v4/reader/object.proto\x12\x13directory.v4.reader\x1a\x19directory/v4/object.proto\x1a\x1ddirectory/v4/pagination.proto\x1a\x1bdirectory/v4/relation.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x86\x01\n" +
	"\x10GetObjectRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12*\n" +
	"\x0ewith_relations\x18\x03 \x01(\bB\x03\xe0A\x01R\rwithRelations\"w\n" +
	"\x11GetObjectResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.directory.v4.ObjectR\x06result\x124\n" +
	"\trelations\x18\x04 \x03(\v2\x16.directory.v4.RelationR\trelations\"t\n" +
	"\x12ListObjectsRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x01R\n" +
	"objectType\x128\n" +
	"\x04page\x18\t \x01(\v2\x1f.directory.v4.PaginationRequestB\x03\xe0A\x01R\x04page\"{\n" +
	"\x13ListObjectsResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.directory.v4.ObjectR\aresults\x124\n" +
	"\x04page\x18\t \x01(\v2 .directory.v4.PaginationResponseR\x04pageB<Z:github.com/aserto-dev/topaz/api/directory/v4/reader;readerb\x06proto3"

var (
	file_directory_v4_reader_object_proto_rawDescOnce sync.Once
	file_directory_v4_reader_object_proto_rawDescData []byte
)

func file_directory_v4_reader_object_proto_rawDescGZIP() []byte {
	file_directory_v4_reader_object_proto_rawDescOnce.Do(func() {
		file_directory_v4_reader_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_reader_object_proto_rawDesc), len(file_directory_v4_reader_object_proto_rawDesc)))
	})
	return file_directory_v4_reader_object_proto_rawDescData
}

var file_directory_v4_reader_object_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_directory_v4_reader_object_proto_goTypes = []any{
	(*GetObjectRequest)(nil),      // 0: directory.v4.reader.GetObjectRequest
	(*GetObjectResponse)(nil),     // 1: directory.v4.reader.GetObjectResponse
	(*ListObjectsRequest)(nil),    // 2: directory.v4.reader.ListObjectsRequest
	(*ListObjectsResponse)(nil),   // 3: directory.v4.reader.ListObjectsResponse
	(*v4.Object)(nil),             // 4: directory.v4.Object
	(*v4.Relation)(nil),           // 5: directory.v4.Relation
	(*v4.PaginationRequest)(nil),  // 6: directory.v4.PaginationRequest
	(*v4.PaginationResponse)(nil), // 7: directory.v4.PaginationResponse
}
var file_directory_v4_reader_object_proto_depIdxs = []int32{
	4, // 0: directory.v4.reader.GetObjectResponse.result:type_name -> directory.v4.Object
	5, // 1: directory.v4.reader.GetObjectResponse.relations:type_name -> directory.v4.Relation
	6, // 2: directory.v4.reader.ListObjectsRequest.page:type_name -> directory.v4.PaginationRequest
	4, // 3: directory.v4.reader.ListObjectsResponse.results:type_name -> directory.v4.Object
	7, // 4: directory.v4.reader.ListObjectsResponse.page:type_name -> directory.v4.PaginationResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_directory_v4_reader_object_proto_init() }
func file_directory_v4_reader_object_proto_init() {
	if File_directory_v4_reader_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_reader_object_proto_rawDesc), len(file_directory_v4_reader_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_reader_object_proto_goTypes,
		DependencyIndexes: file_directory_v4_reader_object_proto_depIdxs,
		MessageInfos:      file_directory_v4_reader_object_proto_msgTypes,
	}.Build()
	File_directory_v4_reader_object_proto = out.File
	file_directory_v4_reader_object_proto_goTypes = nil
	file_directory_v4_reader_object_proto_depIdxs = nil
}
