// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/reader/relation.proto

package reader

import (
	v4 "github.com/aserto-dev/topaz/api/directory/v4"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRelationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type identifier
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject instance identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// subject relation name (optional)
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// materialize relation objects (optional)
	WithObjects   bool `protobuf:"varint,7,opt,name=with_objects,json=withObjects,proto3" json:"with_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationRequest) Reset() {
	*x = GetRelationRequest{}
	mi := &file_directory_v4_reader_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationRequest) ProtoMessage() {}

func (x *GetRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationRequest.ProtoReflect.Descriptor instead.
func (*GetRelationRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_relation_proto_rawDescGZIP(), []int{0}
}

func (x *GetRelationRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetRelationRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetRelationRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GetRelationRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *GetRelationRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetRelationRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *GetRelationRequest) GetWithObjects() bool {
	if x != nil {
		return x.WithObjects
	}
	return false
}

type GetRelationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relation instance
	Result *v4.Relation `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// map of materialized relation objects
	Objects       map[string]*v4.Object `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationResponse) Reset() {
	*x = GetRelationResponse{}
	mi := &file_directory_v4_reader_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationResponse) ProtoMessage() {}

func (x *GetRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationResponse.ProtoReflect.Descriptor instead.
func (*GetRelationResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_relation_proto_rawDescGZIP(), []int{1}
}

func (x *GetRelationResponse) GetResult() *v4.Relation {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetRelationResponse) GetObjects() map[string]*v4.Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type ListRelationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier (optional)
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier (optional)
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name (optional)
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type identifier (optional)
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject instance identifier (optional)
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// subject relation name (optional)
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// materialize relation objects (optional)
	WithObjects bool `protobuf:"varint,7,opt,name=with_objects,json=withObjects,proto3" json:"with_objects,omitempty"`
	// only return relations that do not have a subject relation  (optional)
	WithEmptySubjectRelation bool `protobuf:"varint,8,opt,name=with_empty_subject_relation,json=withEmptySubjectRelation,proto3" json:"with_empty_subject_relation,omitempty"`
	// pagination request (optional)
	Page          *v4.PaginationRequest `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelationsRequest) Reset() {
	*x = ListRelationsRequest{}
	mi := &file_directory_v4_reader_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationsRequest) ProtoMessage() {}

func (x *ListRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationsRequest.ProtoReflect.Descriptor instead.
func (*ListRelationsRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_relation_proto_rawDescGZIP(), []int{2}
}

func (x *ListRelationsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ListRelationsRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ListRelationsRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListRelationsRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *ListRelationsRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ListRelationsRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *ListRelationsRequest) GetWithObjects() bool {
	if x != nil {
		return x.WithObjects
	}
	return false
}

func (x *ListRelationsRequest) GetWithEmptySubjectRelation() bool {
	if x != nil {
		return x.WithEmptySubjectRelation
	}
	return false
}

func (x *ListRelationsRequest) GetPage() *v4.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListRelationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of relation instances
	Results []*v4.Relation `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// map of materialized relation objects
	Objects map[string]*v4.Object `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// pagination response
	Page          *v4.PaginationResponse `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelationsResponse) Reset() {
	*x = ListRelationsResponse{}
	mi := &file_directory_v4_reader_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationsResponse) ProtoMessage() {}

func (x *ListRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_reader_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationsResponse.ProtoReflect.Descriptor instead.
func (*ListRelationsResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_reader_relation_proto_rawDescGZIP(), []int{3}
}

func (x *ListRelationsResponse) GetResults() []*v4.Relation {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListRelationsResponse) GetObjects() map[string]*v4.Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListRelationsResponse) GetPage() *v4.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_directory_v4_reader_relation_proto protoreflect.FileDescriptor

const file_directory_v4_reader_relation_proto_rawDesc = "" +
	"\n" +
	"\"directory/v4/reader/relation.proto\x12\x13directory.v4.reader\x1a\x19directory/v4/object.proto\x1a\x1ddirectory/v4/pagination.proto\x1a\x1bdirectory/v4/relation.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xa1\x02\n" +
	"\x12GetRelationRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\x12&\n" +
	"\fwith_objects\x18\a \x01(\bB\x03\xe0A\x01R\vwithObjects\"\xe8\x01\n" +
	"\x13GetRelationResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.directory.v4.RelationR\x06result\x12O\n" +
	"\aobjects\x18\x02 \x03(\v25.directory.v4.reader.GetRelationResponse.ObjectsEntryR\aobjects\x1aP\n" +
	"\fObjectsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.directory.v4.ObjectR\x05value:\x028\x01\"\xa1\x03\n" +
	"\x14ListRelationsRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x01R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x01R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x01R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x01R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x01R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\x12&\n" +
	"\fwith_objects\x18\a \x01(\bB\x03\xe0A\x01R\vwithObjects\x12B\n" +
	"\x1bwith_empty_subject_relation\x18\b \x01(\bB\x03\xe0A\x01R\x18withEmptySubjectRelation\x128\n" +
	"\x04page\x18\t \x01(\v2\x1f.directory.v4.PaginationRequestB\x03\xe0A\x01R\x04page\"\xa4\x02\n" +
	"\x15ListRelationsResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.directory.v4.RelationR\aresults\x12Q\n" +
	"\aobjects\x18\x02 \x03(\v27.directory.v4.reader.ListRelationsResponse.ObjectsEntryR\aobjects\x124\n" +
	"\x04page\x18\t \x01(\v2 .directory.v4.PaginationResponseR\x04page\x1aP\n" +
	"\fObjectsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.directory.v4.ObjectR\x05value:\x028\x01B<Z:github.com/aserto-dev/topaz/api/directory/v4/reader;readerb\x06proto3"

var (
	file_directory_v4_reader_relation_proto_rawDescOnce sync.Once
	file_directory_v4_reader_relation_proto_rawDescData []byte
)

func file_directory_v4_reader_relation_proto_rawDescGZIP() []byte {
	file_directory_v4_reader_relation_proto_rawDescOnce.Do(func() {
		file_directory_v4_reader_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_reader_relation_proto_rawDesc), len(file_directory_v4_reader_relation_proto_rawDesc)))
	})
	return file_directory_v4_reader_relation_proto_rawDescData
}

var file_directory_v4_reader_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_directory_v4_reader_relation_proto_goTypes = []any{
	(*GetRelationRequest)(nil),    // 0: directory.v4.reader.GetRelationRequest
	(*GetRelationResponse)(nil),   // 1: directory.v4.reader.GetRelationResponse
	(*ListRelationsRequest)(nil),  // 2: directory.v4.reader.ListRelationsRequest
	(*ListRelationsResponse)(nil), // 3: directory.v4.reader.ListRelationsResponse
	nil,                           // 4: directory.v4.reader.GetRelationResponse.ObjectsEntry
	nil,                           // 5: directory.v4.reader.ListRelationsResponse.ObjectsEntry
	(*v4.Relation)(nil),           // 6: directory.v4.Relation
	(*v4.PaginationRequest)(nil),  // 7: directory.v4.PaginationRequest
	(*v4.PaginationResponse)(nil), // 8: directory.v4.PaginationResponse
	(*v4.Object)(nil),             // 9: directory.v4.Object
}
var file_directory_v4_reader_relation_proto_depIdxs = []int32{
	6, // 0: directory.v4.reader.GetRelationResponse.result:type_name -> directory.v4.Relation
	4, // 1: directory.v4.reader.GetRelationResponse.objects:type_name -> directory.v4.reader.GetRelationResponse.ObjectsEntry
	7, // 2: directory.v4.reader.ListRelationsRequest.page:type_name -> directory.v4.PaginationRequest
	6, // 3: directory.v4.reader.ListRelationsResponse.results:type_name -> directory.v4.Relation
	5, // 4: directory.v4.reader.ListRelationsResponse.objects:type_name -> directory.v4.reader.ListRelationsResponse.ObjectsEntry
	8, // 5: directory.v4.reader.ListRelationsResponse.page:type_name -> directory.v4.PaginationResponse
	9, // 6: directory.v4.reader.GetRelationResponse.ObjectsEntry.value:type_name -> directory.v4.Object
	9, // 7: directory.v4.reader.ListRelationsResponse.ObjectsEntry.value:type_name -> directory.v4.Object
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_directory_v4_reader_relation_proto_init() }
func file_directory_v4_reader_relation_proto_init() {
	if File_directory_v4_reader_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_reader_relation_proto_rawDesc), len(file_directory_v4_reader_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_reader_relation_proto_goTypes,
		DependencyIndexes: file_directory_v4_reader_relation_proto_depIdxs,
		MessageInfos:      file_directory_v4_reader_relation_proto_msgTypes,
	}.Build()
	File_directory_v4_reader_relation_proto = out.File
	file_directory_v4_reader_relation_proto_goTypes = nil
	file_directory_v4_reader_relation_proto_depIdxs = nil
}
