// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/manifest.proto

package directory

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// manifest identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// manifest content data
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// last updated timestamp (UTC)
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// object instance etag (optional)
	Etag          string `protobuf:"bytes,23,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_directory_v4_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_directory_v4_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manifest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Manifest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Manifest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

var File_directory_v4_manifest_proto protoreflect.FileDescriptor

const file_directory_v4_manifest_proto_rawDesc = "" +
	"\n" +
	"\x1bdirectory/v4/manifest.proto\x12\fdirectory.v4\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x01\n" +
	"\bManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12>\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tupdatedAt\x12\x17\n" +
	"\x04etag\x18\x17 \x01(\tB\x03\xe0A\x01R\x04etagB8Z6github.com/aserto-dev/topaz/api/directory/v4;directoryb\x06proto3"

var (
	file_directory_v4_manifest_proto_rawDescOnce sync.Once
	file_directory_v4_manifest_proto_rawDescData []byte
)

func file_directory_v4_manifest_proto_rawDescGZIP() []byte {
	file_directory_v4_manifest_proto_rawDescOnce.Do(func() {
		file_directory_v4_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_manifest_proto_rawDesc), len(file_directory_v4_manifest_proto_rawDesc)))
	})
	return file_directory_v4_manifest_proto_rawDescData
}

var file_directory_v4_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_directory_v4_manifest_proto_goTypes = []any{
	(*Manifest)(nil),              // 0: directory.v4.Manifest
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_directory_v4_manifest_proto_depIdxs = []int32{
	1, // 0: directory.v4.Manifest.updated_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_directory_v4_manifest_proto_init() }
func file_directory_v4_manifest_proto_init() {
	if File_directory_v4_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_manifest_proto_rawDesc), len(file_directory_v4_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_manifest_proto_goTypes,
		DependencyIndexes: file_directory_v4_manifest_proto_depIdxs,
		MessageInfos:      file_directory_v4_manifest_proto_msgTypes,
	}.Build()
	File_directory_v4_manifest_proto = out.File
	file_directory_v4_manifest_proto_goTypes = nil
	file_directory_v4_manifest_proto_depIdxs = nil
}
