// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/openapi.proto

package directory

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_directory_v4_openapi_proto protoreflect.FileDescriptor

const file_directory_v4_openapi_proto_rawDesc = "" +
	"\n" +
	"\x1adirectory/v4/openapi.proto\x12\fdirectory.v4\x1a.protoc-gen-openapiv2/options/annotations.protoB\xcf\x03\x92A\x93\x03\x12\xbc\x01\n" +
	"\x11Directory Service\"N\n" +
	"\fAserto, Inc.\x12*https://github.com/aserto-dev/pb-directory\x1a\x12support@aserto.com*R\n" +
	"\x12Apache 2.0 License\x12<https://github.com/aserto-dev/pb-directory/blob/main/LICENSE2\x033.1*\x03\x01\x02\x042\x10application/json:\x10application/jsonZ,\n" +
	"*\n" +
	"\x13AuthorizationHeader\x12\x13\b\x02\x1a\rauthorization \x02b\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00r`\n" +
	"\x18Directory API Reference.\x12Dhttps://github.com/aserto-dev/pb-directory/blob/main/html/index.htmlZ6github.com/aserto-dev/topaz/api/directory/v4;directoryb\x06proto3"

var file_directory_v4_openapi_proto_goTypes = []any{}
var file_directory_v4_openapi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_directory_v4_openapi_proto_init() }
func file_directory_v4_openapi_proto_init() {
	if File_directory_v4_openapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_openapi_proto_rawDesc), len(file_directory_v4_openapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_openapi_proto_goTypes,
		DependencyIndexes: file_directory_v4_openapi_proto_depIdxs,
	}.Build()
	File_directory_v4_openapi_proto = out.File
	file_directory_v4_openapi_proto_goTypes = nil
	file_directory_v4_openapi_proto_depIdxs = nil
}
