# Examples: https://github.com/aserto-dev/topaz/tree/main/docs/examples
---
version: 2
logging:
  prod: true
  log_level: info

directory:
  db_path: ${TOPAZ_DIR}/db/directory.db
  seed_metadata: true
    
remote_directory:
  address: "0.0.0.0:9292"
  insecure: true
    
api:
  health:
    listen_address: "0.0.0.0:8484"
  services:
    authorizer:
      grpc:
        connection_timeout_seconds: 2
        listen_address: "0.0.0.0:8282"
        certs:
          tls_key_path: "${TOPAZ_DIR}/certs/grpc.key"
          tls_cert_path: "${TOPAZ_DIR}/certs/grpc.crt"
          tls_ca_cert_path: "${TOPAZ_DIR}/certs/grpc-ca.crt"
      gateway:
        listen_address: "0.0.0.0:8383"
        certs:
          tls_key_path: "${TOPAZ_DIR}/certs/gateway.key"
          tls_cert_path: "${TOPAZ_DIR}/certs/gateway.crt"
          tls_ca_cert_path: "${TOPAZ_DIR}/certs/gateway-ca.crt"

opa:
  instance_id: "-"
  graceful_shutdown_period_seconds: 2
  local_bundles:
    paths: [${TOPAZ_POLICIES_PATH}]
    skip_verification: true
    watch: true
