package tests_test

import (
	"context"
	"strings"
	"testing"

	"github.com/aserto-dev/topaz/internal/grpc/middlewares/request"
	"github.com/aserto-dev/topaz/internal/header"
	"github.com/google/uuid"
	"github.com/pkg/errors"
	"github.com/stretchr/testify/require"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
)

const (
	output        string = "output"
	testRequestID string = "xyz"
)

var (
	unaryInfo = &grpc.UnaryServerInfo{
		FullMethod: "TestService.UnaryMethod",
	}
	streamInfo = &grpc.StreamServerInfo{
		FullMethod:     "TestService.StreamMethod",
		IsServerStream: true,
	}

	errExpected = errors.New("expected error")
)

func TestUnaryServerWithoutRequestID(t *testing.T) {
	unaryHandler := func(ctx context.Context, req any) (any, error) {
		requestID := header.ExtractRequestID(ctx)
		if requestID == "" {
			t.Errorf("requestID must be generated by interceptor")
		}

		if got, want := header.ExtractRequestID(ctx), requestID; got != want {
			t.Errorf("expect requestID to %q, but got %q", want, got)
		}

		return output, nil
	}

	ctx := grpc.NewContextWithServerTransportStream(context.Background(), ServerTransportStream(""))

	if _, err := request.NewRequestIDMiddleware().Unary()(ctx, testRequestID, unaryInfo, unaryHandler); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestUnaryServerWithRequestID(t *testing.T) {
	assert := require.New(t)
	requestID, err := uuid.NewUUID()
	assert.NoError(err)

	unaryHandler := func(ctx context.Context, req any) (any, error) {
		assert.True(strings.HasPrefix(header.ExtractRequestID(ctx), requestID.String()))
		return output, nil
	}

	ctx := context.Background()
	md := metadata.Pairs(string(header.HeaderAsertoRequestID), requestID.String())
	ctx = grpc.NewContextWithServerTransportStream(ctx, ServerTransportStream(""))
	ctx = metadata.NewIncomingContext(ctx, md)

	_, err = request.NewRequestIDMiddleware().Unary()(ctx, testRequestID, unaryInfo, unaryHandler)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestUnaryServerWithRequestIDChain(t *testing.T) {
	assert := require.New(t)
	requestID, err := uuid.NewUUID()
	assert.NoError(err)

	unaryHandler := func(ctx context.Context, req any) (any, error) {
		gotRequestID := header.ExtractRequestID(ctx)

		requestIDs := strings.Split(gotRequestID, ".")
		if got, want := len(requestIDs), 2; got != want {
			t.Errorf("expect the number of request id to %d, but got %d", want, got)
		}

		if got, want := requestIDs[0], requestID; got != want.String() {
			t.Errorf("expect first request id to %q, but got %q", want, got)
		}

		return output, nil
	}

	ctx := context.Background()
	md := metadata.Pairs(string(header.HeaderAsertoRequestID), requestID.String())
	ctx = grpc.NewContextWithServerTransportStream(ctx, ServerTransportStream(""))
	ctx = metadata.NewIncomingContext(ctx, md)

	if _, err = request.NewRequestIDMiddleware().Unary()(ctx, testRequestID, unaryInfo, unaryHandler); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestUnaryServerWithValidator(t *testing.T) {
	assert := require.New(t)
	requestID := testRequestID

	unaryHandler := func(ctx context.Context, req any) (any, error) {
		if got, want := header.ExtractRequestID(ctx), requestID; got == want {
			t.Errorf("original request id should be invalid")
		}

		return output, nil
	}

	ctx := context.Background()
	md := metadata.Pairs(string(header.HeaderAsertoRequestID), requestID)
	ctx = metadata.NewIncomingContext(ctx, md)
	ctx = grpc.NewContextWithServerTransportStream(ctx, ServerTransportStream(""))
	_, err := request.NewRequestIDMiddleware().Unary()(ctx, testRequestID, unaryInfo, unaryHandler)

	assert.NoError(err)
}

func TestUnaryClient(t *testing.T) {
	assert := require.New(t)
	requestID, err := uuid.NewUUID()
	assert.NoError(err)

	unaryInvoker := func(ctx context.Context, method string, req, reply any, cc *grpc.ClientConn, opts ...grpc.CallOption) error {
		id := request.OutgoingRequestID(ctx)
		assert.Equal(requestID.String(), id)

		return nil
	}

	ctx := header.ContextWithRequestID(context.Background(), requestID.String())

	err = request.NewRequestIDMiddleware().UnaryClient()(ctx, "method", "req", "rep", nil, unaryInvoker)
	assert.NoError(err)
}

func TestStreamClient(t *testing.T) {
	assert := require.New(t)
	requestID, err := uuid.NewUUID()
	assert.NoError(err)

	streamer := func(
		ctx context.Context,
		desc *grpc.StreamDesc,
		cc *grpc.ClientConn,
		method string,
		opts ...grpc.CallOption,
	) (grpc.ClientStream, error) {
		id := request.OutgoingRequestID(ctx)
		assert.Equal(requestID.String(), id)

		return nil, errExpected
	}

	ctx := header.ContextWithRequestID(context.Background(), requestID.String())

	_, err = request.NewRequestIDMiddleware().StreamClient()(ctx, nil, nil, "method", streamer)
	assert.ErrorIs(err, errExpected)
}

func TestStreamServerWithoutRequestID(t *testing.T) {
	streamHandler := func(srv any, stream grpc.ServerStream) error {
		requestID := header.ExtractRequestID(stream.Context())
		if requestID == "" {
			t.Errorf("requestID must be generated by interceptor")
		}

		if got, want := header.ExtractRequestID(stream.Context()), requestID; got != want {
			t.Errorf("expect requestID to %q, but got %q", want, got)
		}

		return nil
	}

	testService := struct{}{}
	ctx := grpc.NewContextWithServerTransportStream(context.Background(), ServerTransportStream(""))
	testStream := ServerStream(ctx)

	err := request.NewRequestIDMiddleware().Stream()(testService, testStream, streamInfo, streamHandler)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStreamServerWithRequestID(t *testing.T) {
	assert := require.New(t)
	requestID, err := uuid.NewUUID()
	assert.NoError(err)

	streamHandler := func(srv any, stream grpc.ServerStream) error {
		requestID := header.ExtractRequestID(stream.Context())
		if requestID == "" {
			t.Errorf("requestID must be generated by interceptor")
		}

		if got, want := header.ExtractRequestID(stream.Context()), requestID; got != want {
			t.Errorf("expect requestID to %q, but got %q", want, got)
		}

		return nil
	}

	testService := struct{}{}
	ctx := context.Background()
	md := metadata.Pairs(string(header.HeaderAsertoRequestID), requestID.String())
	ctx = metadata.NewIncomingContext(ctx, md)
	ctx = grpc.NewContextWithServerTransportStream(ctx, ServerTransportStream(""))
	testStream := ServerStream(ctx)

	err = request.NewRequestIDMiddleware().Stream()(testService, testStream, streamInfo, streamHandler)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStreamServerWithRequestIDChain(t *testing.T) {
	assert := require.New(t)
	requestID, err := uuid.NewUUID()
	assert.NoError(err)

	streamHandler := func(srv any, stream grpc.ServerStream) error {
		gotRequestID := header.ExtractRequestID(stream.Context())

		requestIDs := strings.Split(gotRequestID, ".")
		if got, want := len(requestIDs), 2; got != want {
			t.Errorf("expect the number of request id to %d, but got %d", want, got)
		}

		if got, want := requestIDs[0], requestID; got != want.String() {
			t.Errorf("expect first request id to %q, but got %q", want, got)
		}

		return nil
	}

	testService := struct{}{}
	ctx := context.Background()
	md := metadata.Pairs(string(header.HeaderAsertoRequestID), requestID.String())
	ctx = metadata.NewIncomingContext(ctx, md)
	ctx = grpc.NewContextWithServerTransportStream(ctx, ServerTransportStream(""))
	testStream := ServerStream(ctx)

	err = request.NewRequestIDMiddleware().Stream()(testService, testStream, streamInfo, streamHandler)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStreamServerWithValidator(t *testing.T) {
	assert := require.New(t)
	requestID := testRequestID

	streamHandler := func(srv any, stream grpc.ServerStream) error {
		gotRequestID := header.ExtractRequestID(stream.Context())
		if gotRequestID == requestID {
			t.Errorf("original request id should be invalid")
		}

		return nil
	}

	testService := struct{}{}
	ctx := context.Background()
	md := metadata.Pairs(string(header.HeaderAsertoRequestID), requestID)
	ctx = metadata.NewIncomingContext(ctx, md)
	ctx = grpc.NewContextWithServerTransportStream(ctx, ServerTransportStream(""))
	testStream := ServerStream(ctx)

	err := request.NewRequestIDMiddleware().Stream()(testService, testStream, streamInfo, streamHandler)
	assert.NoError(err)
}
