# yaml-language-server: $schema=./config.json
---
# config schema version.
version: 3

# logger settings.
logging:
  prod: true
  log_level: info
  grpc_log_level: info

# local authentication configuration.
authentication:
  enabled: false
  provider: local
  local:
    keys:
      - "69ba614c64ed4be69485de73d062a00b"
      - "##Ve@rySecret123!!"
    options:
      default:
        enable_api_key: true
        enable_anonymous: false
      overrides:
        paths:
          - /aserto.authorizer.v2.Authorizer/Info
          - /grpc.reflection.v1.ServerReflection/ServerReflectionInfo
          - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
        override:
          enable_anonymous: true
          enable_api_key: false

# debug service settings.
debug:
  enabled: false
  listen_address: :6666
  shutdown_timeout: 0

# health service settings.
health:
  enabled: true
  listen_address: "0.0.0.0:9494"

# metric service settings.
metrics:
  enabled: true
  listen_address: "0.0.0.0:9696"

# topaz services configuration
services:
  topaz:
    grpc:
      listen_address: "0.0.0.0:9292"
      fqdn: ""
      certs:
        tls_key_path: '${TOPAZ_CERTS_DIR}/grpc.key'
        tls_cert_path: '${TOPAZ_CERTS_DIR}/grpc.crt'
        tls_ca_cert_path: '${TOPAZ_CERTS_DIR}/grpc-ca.crt'
      connection_timeout: 5s
    gateway:
      listen_address: "0.0.0.0:9393"
      fqdn: ""
      certs:
        tls_key_path: '${TOPAZ_CERTS_DIR}/gateway.key'
        tls_cert_path: '${TOPAZ_CERTS_DIR}/gateway.crt'
        tls_ca_cert_path: '${TOPAZ_CERTS_DIR}/gateway-ca.crt'
      allowed_origins:
      - http://localhost
      - http://localhost:*
      - https://localhost
      - https://localhost:*
      - https://0.0.0.0:*
      - https://*.aserto.com
      - https://*aserto-console.netlify.app
      allowed_headers:
      - "Authorization"
      - "Content-Type"
      - "If-Match"
      - "If-None-Match"
      - "Depth"
      allowed_methods:
      - "GET"
      - "POST"
      - "HEAD"
      - "DELETE"
      - "PUT"
      - "PATCH"
      - "PROFIND"
      - "MKCOL"
      - "COPY"
      - "MOVE"
      http: false
      read_timeout: 2s
      read_header_timeout: 2s
      write_timeout: 2s
      idle_timeout: 30s
    includes:
      - model
      - reader
      - writer
      - importer
      - exporter
      - authorizer
      - console
      - reflection

# directory configuration.
directory:
  read_timeout: 5s
  write_timeout: 5s

  # directory store configuration.
  store:
    provider: boltdb

    boltdb:
      db_path: '${TOPAZ_DB_DIR}/test.db'

    remote_directory:
      address: "directory.prod.aserto.com:8443"
      tenant_id: ""
      api_key: ""
      token: ""
      client_cert_path: ""
      client_key_path: ""
      ca_cert_path: ""
      insecure: true
      no_tls: false
      no_proxy: false
      headers:
        aserto-account-id: "00000000-1111-2222-3333-444455556666"

# authorizer configuration.
authorizer:
  # Open Policy Agent configuration.
  opa:
    instance_id: "-"
    graceful_shutdown_period_seconds: 2
    # max_plugin_wait_time_seconds: 30 set as default
    local_bundles:
      paths: []
      skip_verification: true
    config:
      services:
        ghcr:
          url: https://ghcr.io
          type: "oci"
          response_header_timeout_seconds: 5
      bundles:
        test:
          service: ghcr
          resource: "ghcr.io/aserto-policies/policy-rebac:latest"
          persist: false
          config:
            polling:
              min_delay_seconds: 60
              max_delay_seconds: 120

  # Decision logger configuration.
  decision_logger:
    provider: self
    self:
      store_directory: "${TOPAZ_DIR}/decisions"
      scribe:
        address: ems.prod.aserto.com:8443
        client_cert_path: "${TOPAZ_DIR}/certs/sidecar-prod.crt"
        client_key_path: "${TOPAZ_DIR}/certs/sidecar-prod.key"
        ack_wait_seconds: 30
        headers:
          Aserto-Tenant-Id: 55cf8ea9-30b2-4f9a-b0bb-021ca12170f3
      shipper:
        publish_timeout_seconds: 2

  # control plane configuration
  controller:
    enabled: true
    server:
      address: relay.prod.aserto.com:8443
      api_key: "0xdeadbeef"
      client_cert_path: "${TOPAZ_DIR}/certs/grpc.crt"
      client_key_path: "${TOPAZ_DIR}/certs/grpc.key"

  # jwt validation configuration
  jwt:
    acceptable_time_skew: 5s
