// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/writer/import.proto

package writer

import (
	v4 "github.com/aserto-dev/topaz/api/directory/v4"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Opcode int32

const (
	Opcode_OPCODE_UNKNOWN               Opcode = 0
	Opcode_OPCODE_SET                   Opcode = 1
	Opcode_OPCODE_DELETE                Opcode = 2
	Opcode_OPCODE_DELETE_WITH_RELATIONS Opcode = 3
)

// Enum value maps for Opcode.
var (
	Opcode_name = map[int32]string{
		0: "OPCODE_UNKNOWN",
		1: "OPCODE_SET",
		2: "OPCODE_DELETE",
		3: "OPCODE_DELETE_WITH_RELATIONS",
	}
	Opcode_value = map[string]int32{
		"OPCODE_UNKNOWN":               0,
		"OPCODE_SET":                   1,
		"OPCODE_DELETE":                2,
		"OPCODE_DELETE_WITH_RELATIONS": 3,
	}
)

func (x Opcode) Enum() *Opcode {
	p := new(Opcode)
	*p = x
	return p
}

func (x Opcode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Opcode) Descriptor() protoreflect.EnumDescriptor {
	return file_directory_v4_writer_import_proto_enumTypes[0].Descriptor()
}

func (Opcode) Type() protoreflect.EnumType {
	return &file_directory_v4_writer_import_proto_enumTypes[0]
}

func (x Opcode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Opcode.Descriptor instead.
func (Opcode) EnumDescriptor() ([]byte, []int) {
	return file_directory_v4_writer_import_proto_rawDescGZIP(), []int{0}
}

type ImportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// operation Opcode enum value
	OpCode Opcode `protobuf:"varint,1,opt,name=op_code,json=opCode,proto3,enum=directory.v4.writer.Opcode" json:"op_code,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ImportRequest_Object
	//	*ImportRequest_Relation
	Msg           isImportRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRequest) Reset() {
	*x = ImportRequest{}
	mi := &file_directory_v4_writer_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRequest) ProtoMessage() {}

func (x *ImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRequest.ProtoReflect.Descriptor instead.
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_import_proto_rawDescGZIP(), []int{0}
}

func (x *ImportRequest) GetOpCode() Opcode {
	if x != nil {
		return x.OpCode
	}
	return Opcode_OPCODE_UNKNOWN
}

func (x *ImportRequest) GetMsg() isImportRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ImportRequest) GetObject() *v4.Object {
	if x != nil {
		if x, ok := x.Msg.(*ImportRequest_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *ImportRequest) GetRelation() *v4.Relation {
	if x != nil {
		if x, ok := x.Msg.(*ImportRequest_Relation); ok {
			return x.Relation
		}
	}
	return nil
}

type isImportRequest_Msg interface {
	isImportRequest_Msg()
}

type ImportRequest_Object struct {
	// object import message
	Object *v4.Object `protobuf:"bytes,5,opt,name=object,proto3,oneof"`
}

type ImportRequest_Relation struct {
	// relation import message
	Relation *v4.Relation `protobuf:"bytes,6,opt,name=relation,proto3,oneof"`
}

func (*ImportRequest_Object) isImportRequest_Msg() {}

func (*ImportRequest_Relation) isImportRequest_Msg() {}

type ImportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object import counter
	//
	// Deprecated: Marked as deprecated in directory/v4/writer/import.proto.
	Object *ImportCounter `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// relation import counter
	//
	// Deprecated: Marked as deprecated in directory/v4/writer/import.proto.
	Relation *ImportCounter `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ImportResponse_Status
	//	*ImportResponse_Counter
	Msg           isImportResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResponse) Reset() {
	*x = ImportResponse{}
	mi := &file_directory_v4_writer_import_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResponse) ProtoMessage() {}

func (x *ImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_import_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResponse.ProtoReflect.Descriptor instead.
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_import_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in directory/v4/writer/import.proto.
func (x *ImportResponse) GetObject() *ImportCounter {
	if x != nil {
		return x.Object
	}
	return nil
}

// Deprecated: Marked as deprecated in directory/v4/writer/import.proto.
func (x *ImportResponse) GetRelation() *ImportCounter {
	if x != nil {
		return x.Relation
	}
	return nil
}

func (x *ImportResponse) GetMsg() isImportResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ImportResponse) GetStatus() *ImportStatus {
	if x != nil {
		if x, ok := x.Msg.(*ImportResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ImportResponse) GetCounter() *ImportCounter {
	if x != nil {
		if x, ok := x.Msg.(*ImportResponse_Counter); ok {
			return x.Counter
		}
	}
	return nil
}

type isImportResponse_Msg interface {
	isImportResponse_Msg()
}

type ImportResponse_Status struct {
	// import status message
	Status *ImportStatus `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type ImportResponse_Counter struct {
	// import counter per type
	Counter *ImportCounter `protobuf:"bytes,5,opt,name=counter,proto3,oneof"`
}

func (*ImportResponse_Status) isImportResponse_Msg() {}

func (*ImportResponse_Counter) isImportResponse_Msg() {}

type ImportCounter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// number of messages received
	Recv uint64 `protobuf:"varint,1,opt,name=recv,proto3" json:"recv,omitempty"`
	// number of messages with OPCODE_SET
	Set uint64 `protobuf:"varint,2,opt,name=set,proto3" json:"set,omitempty"`
	// number of messages with OPCODE_DELETE
	Delete uint64 `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	// number of messages resulting in error
	Error uint64 `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	// counter of type (object|relation)
	Type          string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportCounter) Reset() {
	*x = ImportCounter{}
	mi := &file_directory_v4_writer_import_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCounter) ProtoMessage() {}

func (x *ImportCounter) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_import_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCounter.ProtoReflect.Descriptor instead.
func (*ImportCounter) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_import_proto_rawDescGZIP(), []int{2}
}

func (x *ImportCounter) GetRecv() uint64 {
	if x != nil {
		return x.Recv
	}
	return 0
}

func (x *ImportCounter) GetSet() uint64 {
	if x != nil {
		return x.Set
	}
	return 0
}

func (x *ImportCounter) GetDelete() uint64 {
	if x != nil {
		return x.Delete
	}
	return 0
}

func (x *ImportCounter) GetError() uint64 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ImportCounter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ImportStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC status code (google.golang.org/grpc/codes)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// gRPC status message (google.golang.org/grpc/status)
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// req contains the original import request message
	Req           *ImportRequest `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportStatus) Reset() {
	*x = ImportStatus{}
	mi := &file_directory_v4_writer_import_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportStatus) ProtoMessage() {}

func (x *ImportStatus) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_import_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportStatus.ProtoReflect.Descriptor instead.
func (*ImportStatus) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_import_proto_rawDescGZIP(), []int{3}
}

func (x *ImportStatus) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ImportStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ImportStatus) GetReq() *ImportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

var File_directory_v4_writer_import_proto protoreflect.FileDescriptor

const file_directory_v4_writer_import_proto_rawDesc = "" +
	"\n" +
	" directory/v4/writer/import.proto\x12\x13directory.v4.writer\x1a\x19directory/v4/object.proto\x1a\x1bdirectory/v4/relation.proto\"\xb2\x01\n" +
	"\rImportRequest\x124\n" +
	"\aop_code\x18\x01 \x01(\x0e2\x1b.directory.v4.writer.OpcodeR\x06opCode\x12.\n" +
	"\x06object\x18\x05 \x01(\v2\x14.directory.v4.ObjectH\x00R\x06object\x124\n" +
	"\brelation\x18\x06 \x01(\v2\x16.directory.v4.RelationH\x00R\brelationB\x05\n" +
	"\x03msg\"\x98\x02\n" +
	"\x0eImportResponse\x12>\n" +
	"\x06object\x18\x01 \x01(\v2\".directory.v4.writer.ImportCounterB\x02\x18\x01R\x06object\x12B\n" +
	"\brelation\x18\x02 \x01(\v2\".directory.v4.writer.ImportCounterB\x02\x18\x01R\brelation\x12;\n" +
	"\x06status\x18\x04 \x01(\v2!.directory.v4.writer.ImportStatusH\x00R\x06status\x12>\n" +
	"\acounter\x18\x05 \x01(\v2\".directory.v4.writer.ImportCounterH\x00R\acounterB\x05\n" +
	"\x03msg\"w\n" +
	"\rImportCounter\x12\x12\n" +
	"\x04recv\x18\x01 \x01(\x04R\x04recv\x12\x10\n" +
	"\x03set\x18\x02 \x01(\x04R\x03set\x12\x16\n" +
	"\x06delete\x18\x03 \x01(\x04R\x06delete\x12\x14\n" +
	"\x05error\x18\x04 \x01(\x04R\x05error\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"j\n" +
	"\fImportStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x124\n" +
	"\x03req\x18\x03 \x01(\v2\".directory.v4.writer.ImportRequestR\x03req*a\n" +
	"\x06Opcode\x12\x12\n" +
	"\x0eOPCODE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"OPCODE_SET\x10\x01\x12\x11\n" +
	"\rOPCODE_DELETE\x10\x02\x12 \n" +
	"\x1cOPCODE_DELETE_WITH_RELATIONS\x10\x03B<Z:github.com/aserto-dev/topaz/api/directory/v4/writer;writerb\x06proto3"

var (
	file_directory_v4_writer_import_proto_rawDescOnce sync.Once
	file_directory_v4_writer_import_proto_rawDescData []byte
)

func file_directory_v4_writer_import_proto_rawDescGZIP() []byte {
	file_directory_v4_writer_import_proto_rawDescOnce.Do(func() {
		file_directory_v4_writer_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_writer_import_proto_rawDesc), len(file_directory_v4_writer_import_proto_rawDesc)))
	})
	return file_directory_v4_writer_import_proto_rawDescData
}

var file_directory_v4_writer_import_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_directory_v4_writer_import_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_directory_v4_writer_import_proto_goTypes = []any{
	(Opcode)(0),            // 0: directory.v4.writer.Opcode
	(*ImportRequest)(nil),  // 1: directory.v4.writer.ImportRequest
	(*ImportResponse)(nil), // 2: directory.v4.writer.ImportResponse
	(*ImportCounter)(nil),  // 3: directory.v4.writer.ImportCounter
	(*ImportStatus)(nil),   // 4: directory.v4.writer.ImportStatus
	(*v4.Object)(nil),      // 5: directory.v4.Object
	(*v4.Relation)(nil),    // 6: directory.v4.Relation
}
var file_directory_v4_writer_import_proto_depIdxs = []int32{
	0, // 0: directory.v4.writer.ImportRequest.op_code:type_name -> directory.v4.writer.Opcode
	5, // 1: directory.v4.writer.ImportRequest.object:type_name -> directory.v4.Object
	6, // 2: directory.v4.writer.ImportRequest.relation:type_name -> directory.v4.Relation
	3, // 3: directory.v4.writer.ImportResponse.object:type_name -> directory.v4.writer.ImportCounter
	3, // 4: directory.v4.writer.ImportResponse.relation:type_name -> directory.v4.writer.ImportCounter
	4, // 5: directory.v4.writer.ImportResponse.status:type_name -> directory.v4.writer.ImportStatus
	3, // 6: directory.v4.writer.ImportResponse.counter:type_name -> directory.v4.writer.ImportCounter
	1, // 7: directory.v4.writer.ImportStatus.req:type_name -> directory.v4.writer.ImportRequest
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_directory_v4_writer_import_proto_init() }
func file_directory_v4_writer_import_proto_init() {
	if File_directory_v4_writer_import_proto != nil {
		return
	}
	file_directory_v4_writer_import_proto_msgTypes[0].OneofWrappers = []any{
		(*ImportRequest_Object)(nil),
		(*ImportRequest_Relation)(nil),
	}
	file_directory_v4_writer_import_proto_msgTypes[1].OneofWrappers = []any{
		(*ImportResponse_Status)(nil),
		(*ImportResponse_Counter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_writer_import_proto_rawDesc), len(file_directory_v4_writer_import_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_writer_import_proto_goTypes,
		DependencyIndexes: file_directory_v4_writer_import_proto_depIdxs,
		EnumInfos:         file_directory_v4_writer_import_proto_enumTypes,
		MessageInfos:      file_directory_v4_writer_import_proto_msgTypes,
	}.Build()
	File_directory_v4_writer_import_proto = out.File
	file_directory_v4_writer_import_proto_goTypes = nil
	file_directory_v4_writer_import_proto_depIdxs = nil
}
