// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/writer/manifest.proto

package writer

import (
	v4 "github.com/aserto-dev/topaz/api/directory/v4"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *v4.Manifest           `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetManifestRequest) Reset() {
	*x = SetManifestRequest{}
	mi := &file_directory_v4_writer_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManifestRequest) ProtoMessage() {}

func (x *SetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetManifestRequest.ProtoReflect.Descriptor instead.
func (*SetManifestRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_manifest_proto_rawDescGZIP(), []int{0}
}

func (x *SetManifestRequest) GetManifest() *v4.Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type SetManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *v4.Manifest           `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetManifestResponse) Reset() {
	*x = SetManifestResponse{}
	mi := &file_directory_v4_writer_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManifestResponse) ProtoMessage() {}

func (x *SetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetManifestResponse.ProtoReflect.Descriptor instead.
func (*SetManifestResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *SetManifestResponse) GetManifest() *v4.Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type DeleteManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManifestRequest) Reset() {
	*x = DeleteManifestRequest{}
	mi := &file_directory_v4_writer_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManifestRequest) ProtoMessage() {}

func (x *DeleteManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManifestRequest.ProtoReflect.Descriptor instead.
func (*DeleteManifestRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteManifestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty result
	Result        *emptypb.Empty `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManifestResponse) Reset() {
	*x = DeleteManifestResponse{}
	mi := &file_directory_v4_writer_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManifestResponse) ProtoMessage() {}

func (x *DeleteManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManifestResponse.ProtoReflect.Descriptor instead.
func (*DeleteManifestResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteManifestResponse) GetResult() *emptypb.Empty {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_directory_v4_writer_manifest_proto protoreflect.FileDescriptor

const file_directory_v4_writer_manifest_proto_rawDesc = "" +
	"\n" +
	"\"directory/v4/writer/manifest.proto\x12\x13directory.v4.writer\x1a\x1bdirectory/v4/manifest.proto\x1a\x1bgoogle/protobuf/empty.proto\"H\n" +
	"\x12SetManifestRequest\x122\n" +
	"\bmanifest\x18\x01 \x01(\v2\x16.directory.v4.ManifestR\bmanifest\"I\n" +
	"\x13SetManifestResponse\x122\n" +
	"\bmanifest\x18\x01 \x01(\v2\x16.directory.v4.ManifestR\bmanifest\"'\n" +
	"\x15DeleteManifestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x16DeleteManifestResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x06resultB<Z:github.com/aserto-dev/topaz/api/directory/v4/writer;writerb\x06proto3"

var (
	file_directory_v4_writer_manifest_proto_rawDescOnce sync.Once
	file_directory_v4_writer_manifest_proto_rawDescData []byte
)

func file_directory_v4_writer_manifest_proto_rawDescGZIP() []byte {
	file_directory_v4_writer_manifest_proto_rawDescOnce.Do(func() {
		file_directory_v4_writer_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_writer_manifest_proto_rawDesc), len(file_directory_v4_writer_manifest_proto_rawDesc)))
	})
	return file_directory_v4_writer_manifest_proto_rawDescData
}

var file_directory_v4_writer_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_directory_v4_writer_manifest_proto_goTypes = []any{
	(*SetManifestRequest)(nil),     // 0: directory.v4.writer.SetManifestRequest
	(*SetManifestResponse)(nil),    // 1: directory.v4.writer.SetManifestResponse
	(*DeleteManifestRequest)(nil),  // 2: directory.v4.writer.DeleteManifestRequest
	(*DeleteManifestResponse)(nil), // 3: directory.v4.writer.DeleteManifestResponse
	(*v4.Manifest)(nil),            // 4: directory.v4.Manifest
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_directory_v4_writer_manifest_proto_depIdxs = []int32{
	4, // 0: directory.v4.writer.SetManifestRequest.manifest:type_name -> directory.v4.Manifest
	4, // 1: directory.v4.writer.SetManifestResponse.manifest:type_name -> directory.v4.Manifest
	5, // 2: directory.v4.writer.DeleteManifestResponse.result:type_name -> google.protobuf.Empty
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_directory_v4_writer_manifest_proto_init() }
func file_directory_v4_writer_manifest_proto_init() {
	if File_directory_v4_writer_manifest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_writer_manifest_proto_rawDesc), len(file_directory_v4_writer_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_writer_manifest_proto_goTypes,
		DependencyIndexes: file_directory_v4_writer_manifest_proto_depIdxs,
		MessageInfos:      file_directory_v4_writer_manifest_proto_msgTypes,
	}.Build()
	File_directory_v4_writer_manifest_proto = out.File
	file_directory_v4_writer_manifest_proto_goTypes = nil
	file_directory_v4_writer_manifest_proto_depIdxs = nil
}
