// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/writer/object.proto

package writer

import (
	v4 "github.com/aserto-dev/topaz/api/directory/v4"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object instance
	Object        *v4.Object `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetObjectRequest) Reset() {
	*x = SetObjectRequest{}
	mi := &file_directory_v4_writer_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetObjectRequest) ProtoMessage() {}

func (x *SetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetObjectRequest.ProtoReflect.Descriptor instead.
func (*SetObjectRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_object_proto_rawDescGZIP(), []int{0}
}

func (x *SetObjectRequest) GetObject() *v4.Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type SetObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object instance
	Result        *v4.Object `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetObjectResponse) Reset() {
	*x = SetObjectResponse{}
	mi := &file_directory_v4_writer_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetObjectResponse) ProtoMessage() {}

func (x *SetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetObjectResponse.ProtoReflect.Descriptor instead.
func (*SetObjectResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_object_proto_rawDescGZIP(), []int{1}
}

func (x *SetObjectResponse) GetResult() *v4.Object {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// delete object relations, both object and subject relations  (optional)
	WithRelations bool `protobuf:"varint,3,opt,name=with_relations,json=withRelations,proto3" json:"with_relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_directory_v4_writer_object_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_object_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_object_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteObjectRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *DeleteObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *DeleteObjectRequest) GetWithRelations() bool {
	if x != nil {
		return x.WithRelations
	}
	return false
}

type DeleteObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty result
	Result        *emptypb.Empty `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectResponse) Reset() {
	*x = DeleteObjectResponse{}
	mi := &file_directory_v4_writer_object_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectResponse) ProtoMessage() {}

func (x *DeleteObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_object_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_object_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteObjectResponse) GetResult() *emptypb.Empty {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_directory_v4_writer_object_proto protoreflect.FileDescriptor

const file_directory_v4_writer_object_proto_rawDesc = "" +
	"\n" +
	" directory/v4/writer/object.proto\x12\x13directory.v4.writer\x1a\x19directory/v4/object.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x10SetObjectRequest\x121\n" +
	"\x06object\x18\x01 \x01(\v2\x14.directory.v4.ObjectB\x03\xe0A\x02R\x06object\"A\n" +
	"\x11SetObjectResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.directory.v4.ObjectR\x06result\"\x89\x01\n" +
	"\x13DeleteObjectRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12*\n" +
	"\x0ewith_relations\x18\x03 \x01(\bB\x03\xe0A\x01R\rwithRelations\"F\n" +
	"\x14DeleteObjectResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x06resultB<Z:github.com/aserto-dev/topaz/api/directory/v4/writer;writerb\x06proto3"

var (
	file_directory_v4_writer_object_proto_rawDescOnce sync.Once
	file_directory_v4_writer_object_proto_rawDescData []byte
)

func file_directory_v4_writer_object_proto_rawDescGZIP() []byte {
	file_directory_v4_writer_object_proto_rawDescOnce.Do(func() {
		file_directory_v4_writer_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_writer_object_proto_rawDesc), len(file_directory_v4_writer_object_proto_rawDesc)))
	})
	return file_directory_v4_writer_object_proto_rawDescData
}

var file_directory_v4_writer_object_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_directory_v4_writer_object_proto_goTypes = []any{
	(*SetObjectRequest)(nil),     // 0: directory.v4.writer.SetObjectRequest
	(*SetObjectResponse)(nil),    // 1: directory.v4.writer.SetObjectResponse
	(*DeleteObjectRequest)(nil),  // 2: directory.v4.writer.DeleteObjectRequest
	(*DeleteObjectResponse)(nil), // 3: directory.v4.writer.DeleteObjectResponse
	(*v4.Object)(nil),            // 4: directory.v4.Object
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_directory_v4_writer_object_proto_depIdxs = []int32{
	4, // 0: directory.v4.writer.SetObjectRequest.object:type_name -> directory.v4.Object
	4, // 1: directory.v4.writer.SetObjectResponse.result:type_name -> directory.v4.Object
	5, // 2: directory.v4.writer.DeleteObjectResponse.result:type_name -> google.protobuf.Empty
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_directory_v4_writer_object_proto_init() }
func file_directory_v4_writer_object_proto_init() {
	if File_directory_v4_writer_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_writer_object_proto_rawDesc), len(file_directory_v4_writer_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_writer_object_proto_goTypes,
		DependencyIndexes: file_directory_v4_writer_object_proto_depIdxs,
		MessageInfos:      file_directory_v4_writer_object_proto_msgTypes,
	}.Build()
	File_directory_v4_writer_object_proto = out.File
	file_directory_v4_writer_object_proto_goTypes = nil
	file_directory_v4_writer_object_proto_depIdxs = nil
}
