// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/writer/relation.proto

package writer

import (
	v4 "github.com/aserto-dev/topaz/api/directory/v4"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRelationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relation instance
	Relation      *v4.Relation `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRelationRequest) Reset() {
	*x = SetRelationRequest{}
	mi := &file_directory_v4_writer_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRelationRequest) ProtoMessage() {}

func (x *SetRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRelationRequest.ProtoReflect.Descriptor instead.
func (*SetRelationRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_relation_proto_rawDescGZIP(), []int{0}
}

func (x *SetRelationRequest) GetRelation() *v4.Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type SetRelationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relation instance
	Result        *v4.Relation `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRelationResponse) Reset() {
	*x = SetRelationResponse{}
	mi := &file_directory_v4_writer_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRelationResponse) ProtoMessage() {}

func (x *SetRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRelationResponse.ProtoReflect.Descriptor instead.
func (*SetRelationResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_relation_proto_rawDescGZIP(), []int{1}
}

func (x *SetRelationResponse) GetResult() *v4.Relation {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteRelationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// object relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type identifier
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject instance identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// subject relation name  (optional)
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteRelationRequest) Reset() {
	*x = DeleteRelationRequest{}
	mi := &file_directory_v4_writer_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationRequest) ProtoMessage() {}

func (x *DeleteRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationRequest) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_relation_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRelationRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *DeleteRelationRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *DeleteRelationRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *DeleteRelationRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *DeleteRelationRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *DeleteRelationRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

type DeleteRelationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty result
	Result        *emptypb.Empty `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationResponse) Reset() {
	*x = DeleteRelationResponse{}
	mi := &file_directory_v4_writer_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationResponse) ProtoMessage() {}

func (x *DeleteRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v4_writer_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationResponse.ProtoReflect.Descriptor instead.
func (*DeleteRelationResponse) Descriptor() ([]byte, []int) {
	return file_directory_v4_writer_relation_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRelationResponse) GetResult() *emptypb.Empty {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_directory_v4_writer_relation_proto protoreflect.FileDescriptor

const file_directory_v4_writer_relation_proto_rawDesc = "" +
	"\n" +
	"\"directory/v4/writer/relation.proto\x12\x13directory.v4.writer\x1a\x1bdirectory/v4/relation.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\"M\n" +
	"\x12SetRelationRequest\x127\n" +
	"\brelation\x18\x01 \x01(\v2\x16.directory.v4.RelationB\x03\xe0A\x02R\brelation\"E\n" +
	"\x13SetRelationResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.directory.v4.RelationR\x06result\"\xfc\x01\n" +
	"\x15DeleteRelationRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\"H\n" +
	"\x16DeleteRelationResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x06resultB<Z:github.com/aserto-dev/topaz/api/directory/v4/writer;writerb\x06proto3"

var (
	file_directory_v4_writer_relation_proto_rawDescOnce sync.Once
	file_directory_v4_writer_relation_proto_rawDescData []byte
)

func file_directory_v4_writer_relation_proto_rawDescGZIP() []byte {
	file_directory_v4_writer_relation_proto_rawDescOnce.Do(func() {
		file_directory_v4_writer_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v4_writer_relation_proto_rawDesc), len(file_directory_v4_writer_relation_proto_rawDesc)))
	})
	return file_directory_v4_writer_relation_proto_rawDescData
}

var file_directory_v4_writer_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_directory_v4_writer_relation_proto_goTypes = []any{
	(*SetRelationRequest)(nil),     // 0: directory.v4.writer.SetRelationRequest
	(*SetRelationResponse)(nil),    // 1: directory.v4.writer.SetRelationResponse
	(*DeleteRelationRequest)(nil),  // 2: directory.v4.writer.DeleteRelationRequest
	(*DeleteRelationResponse)(nil), // 3: directory.v4.writer.DeleteRelationResponse
	(*v4.Relation)(nil),            // 4: directory.v4.Relation
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_directory_v4_writer_relation_proto_depIdxs = []int32{
	4, // 0: directory.v4.writer.SetRelationRequest.relation:type_name -> directory.v4.Relation
	4, // 1: directory.v4.writer.SetRelationResponse.result:type_name -> directory.v4.Relation
	5, // 2: directory.v4.writer.DeleteRelationResponse.result:type_name -> google.protobuf.Empty
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_directory_v4_writer_relation_proto_init() }
func file_directory_v4_writer_relation_proto_init() {
	if File_directory_v4_writer_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_writer_relation_proto_rawDesc), len(file_directory_v4_writer_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_directory_v4_writer_relation_proto_goTypes,
		DependencyIndexes: file_directory_v4_writer_relation_proto_depIdxs,
		MessageInfos:      file_directory_v4_writer_relation_proto_msgTypes,
	}.Build()
	File_directory_v4_writer_relation_proto = out.File
	file_directory_v4_writer_relation_proto_goTypes = nil
	file_directory_v4_writer_relation_proto_depIdxs = nil
}
