// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v4/writer/service.proto

package writer

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_directory_v4_writer_service_proto protoreflect.FileDescriptor

const file_directory_v4_writer_service_proto_rawDesc = "" +
	"\n" +
	"!directory/v4/writer/service.proto\x12\x13directory.v4.writer\x1a directory/v4/writer/import.proto\x1a\"directory/v4/writer/manifest.proto\x1a directory/v4/writer/object.proto\x1a\"directory/v4/writer/relation.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x81\r\n" +
	"\x06Writer\x12\xa8\x02\n" +
	"\vSetManifest\x12'.directory.v4.writer.SetManifestRequest\x1a(.directory.v4.writer.SetManifestResponse\"\xc5\x01\x92A\x87\x01\n" +
	"\tdirectory\x12\fSet manifest\x1a\x17Set directory manifest.*\x19directory.v4.manifest.setJ\x1d\n" +
	"\x03304\x12\x16\n" +
	"\x14Object not modified.b\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x024:\bmanifest\"(/api/v4/directory/manifest/{manifest.id}\x12\xa7\x02\n" +
	"\x0eDeleteManifest\x12*.directory.v4.writer.DeleteManifestRequest\x1a+.directory.v4.writer.DeleteManifestResponse\"\xbb\x01\x92A\x90\x01\n" +
	"\tdirectory\x12\x0fDelete manifest\x1a\x1aDelete directory manifest.*\x1cdirectory.v4.manifest.deleteJ\x1d\n" +
	"\x03304\x12\x16\n" +
	"\x14Object not modified.b\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02!*\x1f/api/v4/directory/manifest/{id}\x12\xda\x01\n" +
	"\tSetObject\x12%.directory.v4.writer.SetObjectRequest\x1a&.directory.v4.writer.SetObjectResponse\"~\x92AX\n" +
	"\tdirectory\x12\n" +
	"Set object\x1a\vSet object.*\x17directory.v4.object.setb\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v4/directory/object\x12\x84\x02\n" +
	"\fDeleteObject\x12(.directory.v4.writer.DeleteObjectRequest\x1a).directory.v4.writer.DeleteObjectResponse\"\x9e\x01\x92Aa\n" +
	"\tdirectory\x12\rDelete object\x1a\x0eDelete object.*\x1adirectory.v4.object.deleteb\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x024*2/api/v4/directory/object/{object_type}/{object_id}\x12\xe9\x01\n" +
	"\vSetRelation\x12'.directory.v4.writer.SetRelationRequest\x1a(.directory.v4.writer.SetRelationResponse\"\x86\x01\x92A^\n" +
	"\tdirectory\x12\fSet relation\x1a\rSet relation.*\x19directory.v4.relation.setb\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v4/directory/relation\x12\xf8\x01\n" +
	"\x0eDeleteRelation\x12*.directory.v4.writer.DeleteRelationRequest\x1a+.directory.v4.writer.DeleteRelationResponse\"\x8c\x01\x92Ag\n" +
	"\tdirectory\x12\x0fDelete relation\x1a\x10Delete relation.*\x1cdirectory.v4.relation.deleteb\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v4/directory/relation\x12W\n" +
	"\x06Import\x12\".directory.v4.writer.ImportRequest\x1a#.directory.v4.writer.ImportResponse\"\x00(\x010\x01B<Z:github.com/aserto-dev/topaz/api/directory/v4/writer;writerb\x06proto3"

var file_directory_v4_writer_service_proto_goTypes = []any{
	(*SetManifestRequest)(nil),     // 0: directory.v4.writer.SetManifestRequest
	(*DeleteManifestRequest)(nil),  // 1: directory.v4.writer.DeleteManifestRequest
	(*SetObjectRequest)(nil),       // 2: directory.v4.writer.SetObjectRequest
	(*DeleteObjectRequest)(nil),    // 3: directory.v4.writer.DeleteObjectRequest
	(*SetRelationRequest)(nil),     // 4: directory.v4.writer.SetRelationRequest
	(*DeleteRelationRequest)(nil),  // 5: directory.v4.writer.DeleteRelationRequest
	(*ImportRequest)(nil),          // 6: directory.v4.writer.ImportRequest
	(*SetManifestResponse)(nil),    // 7: directory.v4.writer.SetManifestResponse
	(*DeleteManifestResponse)(nil), // 8: directory.v4.writer.DeleteManifestResponse
	(*SetObjectResponse)(nil),      // 9: directory.v4.writer.SetObjectResponse
	(*DeleteObjectResponse)(nil),   // 10: directory.v4.writer.DeleteObjectResponse
	(*SetRelationResponse)(nil),    // 11: directory.v4.writer.SetRelationResponse
	(*DeleteRelationResponse)(nil), // 12: directory.v4.writer.DeleteRelationResponse
	(*ImportResponse)(nil),         // 13: directory.v4.writer.ImportResponse
}
var file_directory_v4_writer_service_proto_depIdxs = []int32{
	0,  // 0: directory.v4.writer.Writer.SetManifest:input_type -> directory.v4.writer.SetManifestRequest
	1,  // 1: directory.v4.writer.Writer.DeleteManifest:input_type -> directory.v4.writer.DeleteManifestRequest
	2,  // 2: directory.v4.writer.Writer.SetObject:input_type -> directory.v4.writer.SetObjectRequest
	3,  // 3: directory.v4.writer.Writer.DeleteObject:input_type -> directory.v4.writer.DeleteObjectRequest
	4,  // 4: directory.v4.writer.Writer.SetRelation:input_type -> directory.v4.writer.SetRelationRequest
	5,  // 5: directory.v4.writer.Writer.DeleteRelation:input_type -> directory.v4.writer.DeleteRelationRequest
	6,  // 6: directory.v4.writer.Writer.Import:input_type -> directory.v4.writer.ImportRequest
	7,  // 7: directory.v4.writer.Writer.SetManifest:output_type -> directory.v4.writer.SetManifestResponse
	8,  // 8: directory.v4.writer.Writer.DeleteManifest:output_type -> directory.v4.writer.DeleteManifestResponse
	9,  // 9: directory.v4.writer.Writer.SetObject:output_type -> directory.v4.writer.SetObjectResponse
	10, // 10: directory.v4.writer.Writer.DeleteObject:output_type -> directory.v4.writer.DeleteObjectResponse
	11, // 11: directory.v4.writer.Writer.SetRelation:output_type -> directory.v4.writer.SetRelationResponse
	12, // 12: directory.v4.writer.Writer.DeleteRelation:output_type -> directory.v4.writer.DeleteRelationResponse
	13, // 13: directory.v4.writer.Writer.Import:output_type -> directory.v4.writer.ImportResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_directory_v4_writer_service_proto_init() }
func file_directory_v4_writer_service_proto_init() {
	if File_directory_v4_writer_service_proto != nil {
		return
	}
	file_directory_v4_writer_import_proto_init()
	file_directory_v4_writer_manifest_proto_init()
	file_directory_v4_writer_object_proto_init()
	file_directory_v4_writer_relation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v4_writer_service_proto_rawDesc), len(file_directory_v4_writer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_directory_v4_writer_service_proto_goTypes,
		DependencyIndexes: file_directory_v4_writer_service_proto_depIdxs,
	}.Build()
	File_directory_v4_writer_service_proto = out.File
	file_directory_v4_writer_service_proto_goTypes = nil
	file_directory_v4_writer_service_proto_depIdxs = nil
}
