name: pr_checks
on:
  pull_request:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: gitleaks-check
        uses: aserto-dev/gitleaks-action@master
