name: Windows CI Workflow
on:
  push:

jobs:
  build-containers:
    name: Build Containers
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Build
        run: |
          docker build -f Dockerfile.windows .