# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

env:
  GOEXPERIMENT: jsonv2
  GOPRIVATE: github.com/aserto-dev
  DOCKER_BUILDKIT: '1'

vars:
  # repo information
  REGISTRY: ghcr.io
  ORG: aserto-dev
  REPO: topaz
  DESCRIPTION: 'Topaz Authorization Service'
  LICENSE: Apache-2.0

  # dependency versions 
  GO_VER: 'go1.26.5'
  SVU_VER: '3.3.0'
  GOTESTSUM_VER: '1.13.0'
  GOLANGCI_LINT_VER: '2.12.2'
  GORELEASER_VER: '2.14.1'
  SYFT_VER: '1.13.0'

  NO_COLOR: "\x1b[0m"
  OK_COLOR: "\x1b[32;01m"
  ERR_COLOR: "\x1b[31;01m"
  WARN_COLOR: "\x1b[36;01m"
  ATTN_COLOR: "\x1b[33;01m"
